//LOCALHOST
//GUEST COLLECTION
// get all guests
GET http://localhost:8080/guest

### // get guest by id
GET http://localhost:8080/guest/628443e989db2f59bee20bc8

### create guest
POST http://localhost:8080/guest 
content-type:application/json

{
"firstName":"Kelsie","lastName":"Roberts","invitationSent":false,"invitedToCeremony":true,"foodAllergies":{"dairy":true,"gluten":true,"other":"tries to avoid sugar"},"address":"1234, anywhere drive","role":"best friend"
}

### PUT guest/ change it
PUT http://localhost:8080/guest/628ea4f2a7803ca008042ab7
// HTTP/1.1 
content-type:application/json

{
"firstName":"Kelsie","lastName":"Roberts","invitationSent":false,"invitedToCeremony":true,"foodAllergies":{"dairy":true,"gluten":true,"other":"tries to avoid sugar"},"address":"1234, anywhere drive","role":"BFF"
}

### delete guest
DELETE http://localhost:8080/guest/628e478956fcfc7cec304afe


//USER COLLECTION
### // get all users from user collection
GET http://localhost:8080/user

### // get user by id
GET http://localhost:8080/user/62a239d05753710011017540

### create user
POST http://localhost:8080/user
content-type:application/json

{
  "tenant":"dev-jn2i28t1", 
  "connection":"MongoDB", 
  "email":"email4@email.com", 
  "password":"s0safe!!",
  "debug":true,
  "email_verified":false
}

### PUT user/update it
PUT http://localhost:8080/user/628ea4f2a7803ca008042ab7
// HTTP/1.1 
content-type:application/json

{
  "tenant":"dev-jn2i28t1", 
  "connection":"MongoDB", 
  "email":"email4@email.com", 
  "password":"s0safe!!",
  "debug":true,
  "email_verified":false
}

### delete user
DELETE http://localhost:8080/user/62a239d05753710011017540



//PRODUCTION
### // get all guests
GET https://cse341-wedding-project.herokuapp.com/guest

### // get guest by id
GET https://cse341-wedding-project.herokuapp.com/guest/628443e989db2f59bee20bc8

### create guest
POST https://cse341-wedding-project.herokuapp.com/guest
content-type:application/json

{
"firstName":"Kelsie","lastName":"Roberts","invitationSent":false,"invitedToCeremony":true,"foodAllergies":{"dairy":true,"gluten":true,"other":"tries to avoid sugar"},"address":"1234, anywhere drive","role":"best friend"
}

### update guest
PUT https://cse341-wedding-project.herokuapp.com/guest
content-type:application/json

{
"firstName":"Kelsie","lastName":"Roberts","invitationSent":false,"invitedToCeremony":true,"foodAllergies":{"dairy":true,"gluten":true,"other":"tries to avoid sugar"},"address":"1234, anywhere drive","role":"BFF"
}

### delete guest
DELETE http://cse341-wedding-project.herokuapp.com/guest/62729f54607b3826fadefe68

//USER COLLECTION
### // get all users from user collection
GET http://cse341-wedding-project.herokuapp.com/user

### // get user by id
GET https://cse341-wedding-project.herokuapp.com/user/628443e989db2f59bee20bc8

### create user
POST https://cse341-wedding-project.herokuapp.com/user
content-type:application/json

{
  "tenant":"dev-jn2i28t1", 
  "connection":"MongoDB", 
  "email":"email4@email.com", 
  "password":"s0safe!!",
  "debug":true,
  "email_verified":false
}

### update user
PUT https://cse341-wedding-project.herokuapp.com/user
content-type:application/json

{
  "tenant":"dev-jn2i28t1", 
  "connection":"MongoDB", 
  "email":"email4@email.com", 
  "password":"s0safe!!",
  "debug":true,
  "email_verified":false
}

### delete user
DELETE http://cse341-wedding-project.herokuapp.com/user/62729f54607b3826fadefe68

###
curl --request POST \
  --url https://dev-jn2i28t1.us.auth0.com/oauth/token \
  --header 'content-type: application/json' \
  --data '{"client_id":"FgRvsvshcDnY1Nx76KFGSx8OsM0Ro0S1","client_secret":"flj8DmN7IHQyPdOQP12NHkfUxs3lADOc4id_7xSCf-EJ5b-wEOsiGAKdOF3n7aUH","audience":"wk7-class-activity","grant_type":"client_credentials"}'